server.port=8080

# RabbitMQ
spring.rabbitmq.host=10.68.18.8
spring.rabbitmq.port=5672
spring.rabbitmq.username=sunny
spring.rabbitmq.password=sunny@2025
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1

# KingbaseES v8 datasource
spring.datasource.url=jdbc:postgresql://10.68.18.5:54321/qixiao-apaas?currentSchema=qixiao-apaas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=SYSTEM
spring.datasource.password=T!3>kGit70DZ
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# MQTT connection
mqtt.url=tcp://10.68.18.8:1883
mqtt.client-id=hltgq-mq-${random.uuid}
mqtt.username=sunny
mqtt.password=sunny@2025
mqtt.topics=HLTData

# log
logging.file.name=/app/logs/hltgq-mq.log
# MQTT??????????????????????????
logging.level.com.qgyun.hltgq.hltgqmq.config.MqttConfig=DEBUG
